
title: Amirali Sharifian Resume
url: 'http://www.sfu.ca/~amiralis/'
baseurl: 'http://www.sfu.ca/~amiralis' #change it according to your repository name
#baseurl: '/online-cv' #change it according to your repository name


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6


#Profile information
name: Amirali Sharifian
tagline: PhD Student
university: Simon Fraser University
pic: amirali.jpg  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

#sidebar links
email: amiralis@sfu.ca
phone: 778 952 3288
#website: blog.webjeda.com #do not add http://
# website: scholar.google.ca/citations?user=F6HjMj4AAAAJ&hl=en&oi=ao
linkedin: amsharifian
github: amsharifian
twitter: '@amMoriss'
dblp: amsharifian
scholar: amsharifian


# Tracker
analytics: UA-83979019-1
#Update all the sections by editing the files inside _includes folder.
